/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculation;

/**
 *
 * @author Lenovo
 */
public class Calculator extends javax.swing.JFrame {
    double First_Number;
    double Second_Number;
    double Result;
    String Calculate;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Display = new javax.swing.JTextField();
        Button_1 = new javax.swing.JButton();
        Button_2 = new javax.swing.JButton();
        Button_3 = new javax.swing.JButton();
        Button_0 = new javax.swing.JButton();
        Button_4 = new javax.swing.JButton();
        Button_5 = new javax.swing.JButton();
        Button_6 = new javax.swing.JButton();
        Button_7 = new javax.swing.JButton();
        Button_8 = new javax.swing.JButton();
        Button_9 = new javax.swing.JButton();
        Button_10 = new javax.swing.JButton();
        Button_11 = new javax.swing.JButton();
        Button_12 = new javax.swing.JButton();
        Button_13 = new javax.swing.JButton();
        Button_14 = new javax.swing.JButton();
        Button_15 = new javax.swing.JButton();
        Button_16 = new javax.swing.JButton();
        Button_00 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text_Display.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        Text_Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Button_1.setBackground(new java.awt.Color(51, 255, 0));
        Button_1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_1.setText("1");
        Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1ActionPerformed(evt);
            }
        });

        Button_2.setBackground(new java.awt.Color(51, 255, 0));
        Button_2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_2.setText("2");
        Button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2ActionPerformed(evt);
            }
        });

        Button_3.setBackground(new java.awt.Color(51, 255, 0));
        Button_3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_3.setText("3");
        Button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3ActionPerformed(evt);
            }
        });

        Button_0.setBackground(new java.awt.Color(51, 255, 0));
        Button_0.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_0.setText("0");
        Button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_0ActionPerformed(evt);
            }
        });

        Button_4.setBackground(new java.awt.Color(51, 255, 0));
        Button_4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_4.setText("4");
        Button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4ActionPerformed(evt);
            }
        });

        Button_5.setBackground(new java.awt.Color(51, 255, 0));
        Button_5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_5.setText("5");
        Button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5ActionPerformed(evt);
            }
        });

        Button_6.setBackground(new java.awt.Color(51, 255, 0));
        Button_6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_6.setText("6");
        Button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6ActionPerformed(evt);
            }
        });

        Button_7.setBackground(new java.awt.Color(51, 255, 0));
        Button_7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_7.setText("7");
        Button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_7ActionPerformed(evt);
            }
        });

        Button_8.setBackground(new java.awt.Color(51, 255, 0));
        Button_8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_8.setText("8");
        Button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_8ActionPerformed(evt);
            }
        });

        Button_9.setBackground(new java.awt.Color(51, 255, 0));
        Button_9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_9.setText("9");
        Button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_9ActionPerformed(evt);
            }
        });

        Button_10.setBackground(new java.awt.Color(51, 255, 0));
        Button_10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_10.setText("C");
        Button_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_10ActionPerformed(evt);
            }
        });

        Button_11.setBackground(new java.awt.Color(51, 255, 0));
        Button_11.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_11.setText("+");
        Button_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_11ActionPerformed(evt);
            }
        });

        Button_12.setBackground(new java.awt.Color(51, 255, 0));
        Button_12.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_12.setText("-");
        Button_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_12ActionPerformed(evt);
            }
        });

        Button_13.setBackground(new java.awt.Color(51, 255, 0));
        Button_13.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_13.setText("*");
        Button_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_13ActionPerformed(evt);
            }
        });

        Button_14.setBackground(new java.awt.Color(51, 255, 0));
        Button_14.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_14.setText("/");
        Button_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_14ActionPerformed(evt);
            }
        });

        Button_15.setBackground(new java.awt.Color(51, 255, 0));
        Button_15.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_15.setText(".");
        Button_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_15ActionPerformed(evt);
            }
        });

        Button_16.setBackground(new java.awt.Color(51, 255, 0));
        Button_16.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_16.setText("=");
        Button_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_16ActionPerformed(evt);
            }
        });

        Button_00.setBackground(new java.awt.Color(51, 255, 0));
        Button_00.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button_00.setText("00");
        Button_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_00ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_Display, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_00, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Button_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Button_16, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(35, 35, 35)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Button_11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Button_14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Text_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(177, 177, 177)
                                    .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_15, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(177, 177, 177)
                                    .addComponent(Button_12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(Button_11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Button_10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187)))
                        .addGap(34, 34, 34)
                        .addComponent(Button_14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_00, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3ActionPerformed
       String EnterNumber = Text_Display.getText() + Button_3.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_3ActionPerformed

    private void Button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_4.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_4ActionPerformed

    private void Button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_5.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_5ActionPerformed

    private void Button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_6.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_6ActionPerformed

    private void Button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_7ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_7.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_7ActionPerformed

    private void Button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_8ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_8.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_8ActionPerformed

    private void Button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_9ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_9.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_9ActionPerformed

    private void Button_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_10ActionPerformed
        Text_Display.setText("");
    }//GEN-LAST:event_Button_10ActionPerformed

    private void Button_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_15ActionPerformed
       String EnterNumber = Text_Display.getText() + Button_15.getText();
       Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_15ActionPerformed

    private void Button_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_16ActionPerformed
        String Answer;
        Second_Number = Double.parseDouble(Text_Display.getText());
        if(Calculate == "+"){
            Result = First_Number + Second_Number;
            Answer = String.format("%.0f", Result);
            Text_Display.setText(Answer);
        }
        else if(Calculate == "-"){
            Result = First_Number - Second_Number;
            Answer = String.format("%.0f", Result);
            Text_Display.setText(Answer);
        } 
         else if(Calculate == "/"){
            Result = First_Number / Second_Number;
            Answer = String.format("%.0f", Result);
            Text_Display.setText(Answer);
        } 
          else if(Calculate == "%"){
            Result = First_Number % Second_Number;
            Answer = String.format("%.0f", Result);
            Text_Display.setText(Answer);
        } 
         else if(Calculate == "*"){
            Result = First_Number * Second_Number;
            Answer = String.format("%.0f", Result);
            Text_Display.setText(Answer);
        } 
        
    }//GEN-LAST:event_Button_16ActionPerformed

    private void Button_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_00ActionPerformed
       String EnterNumber = Text_Display.getText() + Button_00.getText();
       Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_00ActionPerformed

    private void Button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_2ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_2.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_2ActionPerformed

    private void Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_1ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_1.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_1ActionPerformed

    private void Button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_0ActionPerformed
        String EnterNumber = Text_Display.getText() + Button_0.getText();
        Text_Display.setText(EnterNumber);
    }//GEN-LAST:event_Button_0ActionPerformed

    private void Button_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_11ActionPerformed
        First_Number = Double.parseDouble(Text_Display.getText());
        Text_Display.setText("");
        Calculate = "+";        
    }//GEN-LAST:event_Button_11ActionPerformed

    private void Button_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_12ActionPerformed
        First_Number = Double.parseDouble(Text_Display.getText());
        Text_Display.setText("");
        Calculate = "-";
    }//GEN-LAST:event_Button_12ActionPerformed

    private void Button_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_14ActionPerformed
        First_Number = Double.parseDouble(Text_Display.getText());
        Text_Display.setText("");
        Calculate = "/";
    }//GEN-LAST:event_Button_14ActionPerformed

    private void Button_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_13ActionPerformed
        First_Number = Double.parseDouble(Text_Display.getText());
        Text_Display.setText("");
        Calculate = "*";    }//GEN-LAST:event_Button_13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_0;
    private javax.swing.JButton Button_00;
    private javax.swing.JButton Button_1;
    private javax.swing.JButton Button_10;
    private javax.swing.JButton Button_11;
    private javax.swing.JButton Button_12;
    private javax.swing.JButton Button_13;
    private javax.swing.JButton Button_14;
    private javax.swing.JButton Button_15;
    private javax.swing.JButton Button_16;
    private javax.swing.JButton Button_2;
    private javax.swing.JButton Button_3;
    private javax.swing.JButton Button_4;
    private javax.swing.JButton Button_5;
    private javax.swing.JButton Button_6;
    private javax.swing.JButton Button_7;
    private javax.swing.JButton Button_8;
    private javax.swing.JButton Button_9;
    private javax.swing.JTextField Text_Display;
    // End of variables declaration//GEN-END:variables
}
